# name: constant_mocap.py 
# description: constants for processing the mocap data


MOCAP_SAMPLING_RATE = 100 # Hz
FP_SAMPLING_RATE    = 1000 # Hz

FILTER_CUTOFF_MOCAP = 15 # Hz


# --- HAKnee --- #
# For visualization
HAKNEE_THIGH_CLUSTER_LIST_R = ['RTSP', 'RTIP', 'RTIA', 'RTSA']
HAKNEE_THIGH_CLUSTER_LIST_L = ['LTSP', 'LTIP', 'LTIA', 'LTSA']
HAKNEE_SHANK_CLUSTER_LIST_R = ['RSSP', 'RSIP', 'RSIA', 'RSSA']
HAKNEE_SHANK_CLUSTER_LIST_L = ['LSSP', 'LSIP', 'LSIA', 'LSSA']

HAKNEE_KNEE_ANATOMICAL_LIST  = ['RLK', 'RMK', 'LLK', 'LMK']
HAKNEE_HIP_ANATOMICAL_LIST   = ['RGTR', 'LGTR']
HAKNEE_ANKLE_ANATOMICAL_LIST = ['RLA', 'RMA', 'LMA', 'LLA']

# For IK
HAKNEE_THIGH_CLUSTER_IK_LIST_R = ['RTSP', 'RTIA', 'RTSA']
HAKNEE_SHANK_CLUSTER_IK_LIST_R = ['RSSP', 'RSIA', 'RSSA']
HAKNEE_THIGH_CLUSTER_IK_LIST_L = ['LTSP', 'LTIA', 'LTSA']
HAKNEE_SHANK_CLUSTER_IK_LIST_L = ['LSSP', 'LSIA', 'LSSA']












